export const INSTALLATION_HAS_SESSION = "INSTALLATION_HAS_SESSION";
export const INVALID_RESPONSE_RECEIVED = "INVALID_RESPONSE_RECEIVED";

export default {
    INSTALLATION_HAS_SESSION,
    INVALID_RESPONSE_RECEIVED
};
